version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
     - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
     - ./docker_compose_storage/postgres-data:/var/lib/postgresql/data
    # networks:
    #   - ai_chat-backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - postgres
    # networks:
    #   - ai_chat-frontend
    #   - ai_chat-backend

  redis:
    image: redis/redis-stack:latest
    container_name: redis-cache
    command: redis-stack-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./docker_compose_storage/redis-data:/data
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # networks:
    #   - ai_chat-backend


# networks:
#   ai_chat-frontend:
#   ai_chat-backend:
